In [8]:
# we can give alias name to a module in import statement itself
import datetime as dt
d=dt.datetime.now()
print(d)
print(d.day)

2019-11-21 09:58:19.108677
21


In [13]:
#to print a entire month calendar u need to import calendar module
#in that month is function which takes 2 arguments
#1---> is year
#2----> is month
import calendar as c
print(c.month(2020,6))

     June 2020
Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7
 8  9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30



In [15]:
#weekday is a function which prints the index of weekday it takes 3 arguments
#1---->year
#2---->month
#3---->day
## index of weekdays
#0--->Monday
#1--->tuesday
#2--->wednesday
#3--->thursday
#4--->friday
#5--->saturday
#6--->sunday
c.weekday(2020,6,1)

2

In [16]:
#it count's no.of leap years in between given range
c.leapdays(2000,2020)

5

In [17]:
#it return's if the given year leap or not
c.isleap(2019)

False

In [18]:
import time as t
t.localtime(t.time())


time.struct_time(tm_year=2019, tm_mon=11, tm_mday=21, tm_hour=10, tm_min=29, tm_sec=39, tm_wday=3, tm_yday=325, tm_isdst=0)

In [25]:
from tkinter import *
tk=Tk()
canvas=Canvas(tk,width=200,height=300)
canvas.pack()
canvas.create_arc(10,10,200,100,extent=180,style=ARC)
tk.mainloop()

In [26]:
import turtle
t=turtle.Pen()
t.color(1,0,0)
t.begin_fill()
t.forward(1000)
t.left(90)
t.forward(20)
t.right(90)
t.forward(20)
t.left(90)
t.forward(60)


In [4]:
from tkinter import *
tk=Tk()
btn=Button(tk,text="click ")
btn.pack()
tk.mainloop()

In [5]:
import numpy as np
data=np.random.randn(2,3)
print(data)
print(data*10)
print(data+data)

[[ 0.65281095  1.74279076  1.40914552]
 [-0.4110421  -1.5049633   1.10695617]]
[[  6.52810955  17.42790758  14.0914552 ]
 [ -4.11042099 -15.049633    11.06956172]]
[[ 1.30562191  3.48558152  2.81829104]
 [-0.8220842  -3.0099266   2.21391234]]


In [6]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [8]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [10]:
arr**.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [13]:
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [14]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [18]:
data=np.random.randn(2,3)
data

array([[ 0.11318672,  0.6157951 , -1.57727083],
       [ 0.14751258,  0.58820991,  0.33352364]])

In [33]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr[5]

5

In [35]:
arr[5:8]

array([5, 6, 7])

In [36]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [37]:
arr_slice=arr[5:8]
arr_slice

array([12, 12, 12])

In [38]:
arr_slice[1]=12345
print(arr_slice)
print(arr)

[   12 12345    12]
[    0     1     2     3     4    12 12345    12     8     9]


In [39]:
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [40]:
arr_slice

array([64, 64, 64])

In [41]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [42]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [45]:
arr2d[1,:2]

array([4, 5])

In [46]:
arr2d[:2,2]

array([3, 6])

In [47]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [51]:
arr2d[:2,1:]=9
arr2d

array([[1, 9, 9],
       [4, 9, 9],
       [7, 8, 9]])

In [56]:
name=np.array(['nrk','kh','nsr','nrk','nsr','bvk','nrk'])
data=np.random.randn(7,4)
print(name)
print(data)

['nrk' 'kh' 'nsr' 'nrk' 'nsr' 'bvk' 'nrk']
[[ 0.12944492  0.70053194 -0.11095583  1.13372478]
 [-0.25842708  0.12281602 -0.83213828  0.44711872]
 [ 1.01150308  0.48825045 -2.17981202  0.64219566]
 [ 1.01250252 -0.27335611 -1.77179606 -1.7584609 ]
 [-1.03538865  0.46720113 -1.1213192  -0.59684343]
 [-0.34770196  2.31573708  0.86272957  1.06728687]
 [-0.36863436 -0.85172365  0.12375629  0.96585961]]


In [57]:
name=="nrk"

array([ True, False, False,  True, False, False,  True])

In [59]:
data[name=="nrk"]

array([[ 0.12944492,  0.70053194, -0.11095583,  1.13372478],
       [ 1.01250252, -0.27335611, -1.77179606, -1.7584609 ],
       [-0.36863436, -0.85172365,  0.12375629,  0.96585961]])

In [60]:
data[name=='nrk',2:]

array([[-0.11095583,  1.13372478],
       [-1.77179606, -1.7584609 ],
       [ 0.12375629,  0.96585961]])

In [61]:
data[name=='nrk',3]

array([ 1.13372478, -1.7584609 ,  0.96585961])

In [62]:
name!='nrk'

array([False,  True,  True, False,  True,  True, False])

In [63]:
data[~(name=='nrk')]

array([[-0.25842708,  0.12281602, -0.83213828,  0.44711872],
       [ 1.01150308,  0.48825045, -2.17981202,  0.64219566],
       [-1.03538865,  0.46720113, -1.1213192 , -0.59684343],
       [-0.34770196,  2.31573708,  0.86272957,  1.06728687]])

In [64]:
cond=name=='nrk'

In [65]:
data[~cond]

array([[-0.25842708,  0.12281602, -0.83213828,  0.44711872],
       [ 1.01150308,  0.48825045, -2.17981202,  0.64219566],
       [-1.03538865,  0.46720113, -1.1213192 , -0.59684343],
       [-0.34770196,  2.31573708,  0.86272957,  1.06728687]])

In [67]:
mask=(name=='nrk')|(name=='nsr')
mask

array([ True, False,  True,  True,  True, False,  True])

In [68]:
data[mask]

array([[ 0.12944492,  0.70053194, -0.11095583,  1.13372478],
       [ 1.01150308,  0.48825045, -2.17981202,  0.64219566],
       [ 1.01250252, -0.27335611, -1.77179606, -1.7584609 ],
       [-1.03538865,  0.46720113, -1.1213192 , -0.59684343],
       [-0.36863436, -0.85172365,  0.12375629,  0.96585961]])

In [70]:
data[data<0]=0
data

array([[0.12944492, 0.70053194, 0.        , 1.13372478],
       [0.        , 0.12281602, 0.        , 0.44711872],
       [1.01150308, 0.48825045, 0.        , 0.64219566],
       [1.01250252, 0.        , 0.        , 0.        ],
       [0.        , 0.46720113, 0.        , 0.        ],
       [0.        , 2.31573708, 0.86272957, 1.06728687],
       [0.        , 0.        , 0.12375629, 0.96585961]])

In [71]:
data[name!='nsr']=7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.01150308, 0.48825045, 0.        , 0.64219566],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.46720113, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ]])

In [74]:
ar=np.empty((8,4))
for i in range(8):
    ar[i]=i
ar

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [76]:
ar[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [78]:
ar[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [80]:
ar=np.arange(32).reshape((8,4))
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [81]:
ar[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [82]:
ar[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [84]:
ar.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [86]:
np.dot(ar.T,ar)

array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])

In [89]:
ar=np.arange(32).reshape((2,2,8))
ar

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]]])

In [90]:
ar.transpose((1,0,2))

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [16, 17, 18, 19, 20, 21, 22, 23]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15],
        [24, 25, 26, 27, 28, 29, 30, 31]]])

In [91]:
ar.swapaxes(1,2)

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11],
        [ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]],

       [[16, 24],
        [17, 25],
        [18, 26],
        [19, 27],
        [20, 28],
        [21, 29],
        [22, 30],
        [23, 31]]])

In [92]:
import pandas as pd
obj=pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [93]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [94]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [95]:
obj2=pd.Series([4,7,-5,3],index=['d','b','a','c'])

obj

0    4
1    7
2   -5
3    3
dtype: int64

In [96]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [97]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [99]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [100]:
'b' in obj2

True

In [101]:
'e' in obj2

False

In [102]:
sdata={'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}
obj3=pd.Series(sdata)

In [103]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64